import Head from 'next/head'
import styles from '../styles/Home.module.css'
import socket from '../services/socketio';
import { useEffect, useState } from 'react';

export default function Home() {
  const [info, setInfo] = useState();

  useEffect(() => {
    socket.on('info', (data) => {
      setInfo(data)
    })
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Telemetria - Poente</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{info}</h1>
      </main>
    </div>
  )
}
